### PR TITLE
LPS-91318 Add integration tests

### PR DESCRIPTION
**Pull request by marcelabc**

### CODE REVIEW

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielwas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69885. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
