### PR TITLE
LPS-133889 Remove the delete form call from delete method

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
@guilhermecamacho

**Comment by gabrielwas** [comment]
@guilhermedcamacho

**Comment by guilhermedcamacho** [comment]
> @guilhermedcamacho

LGTM :+1:

**Comment by gabrielwas** [comment]
ci:forward

**Pull request closed without merging**
