### PR TITLE
LPS-115615 Add ConcurrentMap to manage native objects

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test

**Comment by gabrielwas** [comment]
ci:test

**Comment by jeyvison** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielwas** [comment]
ci:test:backend

**Comment by gabrielwas** [comment]
ci:test:backend

**Pull request closed without merging**
