### PR TITLE
LPS-99306

### PR DESCRIPTION
**Pull request by brunofarache**
ci:test:lpkg

### CODE REVIEW

**Comment by brunofarache** [comment]
ci:test:lpkg

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielwas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76609. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
