### PR TITLE
LPS-118301 Revert "LPS-117776 create a method to fetch structure layout by structure version id"

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:forward

**Comment by rodrigocunhaa** [comment]
Just started reviewing :)

**Comment by interaminense** [comment]
Just started reviewing :)

**Pull request closed without merging**
