### PR TITLE
LPS-90953 Replace call of search structures

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:sf

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@gabrielwas looks like everything passed, it's just waiting on `modules-unit-project-templates-jdk8` to finish, and I doubt your pull will break this batch.
results: https://test-1-14.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4418/jenkins-report.html

**Comment by gabrielwas** [comment]
@jpince I just run baseline and I'm running ci tests again. I'll send it to Brian after it pass.

**Pull request closed without merging**
