### PR TITLE
LPS-119290 Handle cases of autoFill and jumpToPage actions

### PR DESCRIPTION
**Pull request by carolmariaabb**
https://issues.liferay.com/browse/LPS-119290

### CODE REVIEW

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Comment by gabrielwas** [comment]
Just started reviewing :)

**Pull request closed without merging**
