### PR TITLE
LPS-92352 Add DDMStructureLayout search feature

### PR DESCRIPTION
**Pull request by mclomello**
@gabrielwas

### CODE REVIEW

**Comment by mclomello** [comment]
ci:test:sf

**Comment by mclomello** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gabrielwas** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70378. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
