### PR TITLE
LPS-107737 Adjust tests

### PR DESCRIPTION
**Pull request by gabrielwas**

### CODE REVIEW

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@gabrielwas, your pull request test has been aborted. We are sorry for the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by gabrielwas** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
ci:stop

**Pull request closed without merging**
